### ISSUE TITLE
Publish to Pypi

### ISSUE THREAD

**Issue by trypsynth** [cartertemm/logsetup#1]
I've gotten extended usage out of this library. It's very useful, and does log initialization easier and better than anything else I've tried.

I think it would be great if it was published to Pypi though, so I don't have to download from a specific gitHub commit to know that stuff won't possibly unexpectedly break, plus it would give the library more reach.

**Comment by cartertemm** [comment]
Hey there,

Glad you like the library.

Getting the package on pip should be very simple (in theory). The only problem I can foresee is [this issue](https://github.com/pypa/pip/issues/6301).

We link to the mailgun-api repo directly, which is disallowed by PYPI and made unnecessarily complicated with wheels. Two solutions:

- Get mailgun-api uploaded. I'm a maintainer of the org so this should be possible
- Include it as a hard dependency

Probably going to focus on the former, then I'll revisit.

Thanks

**Comment by trypsynth** [comment]
Awesome, thanks so much :)

**Comment by cartertemm** [comment]
I temporarily opted for the second option. You should now be able to:

```
pip install logsetup==1.1
```
